### ISSUE TITLE
Create Game Tests

### ISSUE THREAD

**Issue by jacobpoulton** [engteam14/yorkpirates2#6]
Tests for the main game functionality itself. Should mainly be focused on making sure all requirements are met.

### Tasks Required to Complete

[**View Testing Plan**](https://docs.google.com/spreadsheets/d/1NZDvXJrVbR53u_dhoxektVIaCEYP0zJUZzGVhlPFxjc/edit?usp=sharing)

- [x] Create a first test to ensure it works
- [x] Go over requirements and decide on all further tests to make
- [ ] Game Tests
  - [ ] Ship Tests
    - [x] #10
    - [x] #11
    - [x] #12
    - [x] #13
    - [x] #14
  - [x] Building Tests
    - [x] #17
    - [x] #18
  - [x] Component Tests
    - [x] #41 
  - [ ] Game State Tests
    - [x] #15
    - [x] #16
    - [x] #19
- [ ] Review that no more are needed
