### ISSUE TITLE
Set up Continuous Integration

### ISSUE THREAD

**Issue by jacobpoulton** [engteam14/yorkpirates2#7]
Continuous Integration with GitHub actions needs to be set up to run all of our tests whenever a pull request is made.

### Tasks Required to Complete

- [x] Works with at minimum one Utility, Asset and Game test.
- [x] Works with all initial tests.
- [x] Deploys test report to website.
- [x] Deploys documentation to website.
- [x] Deploys jar to website.

This should therefore work for future tests to be implemented with new functionality.
